# Generated by Django 4.2.21 on 2025-07-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_lote', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_admision', models.DateField()),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='LugarDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmbalaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ordenventa',
            options={'verbose_name': 'Orden de venta', 'verbose_name_plural': 'Órdenes de venta'},
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='estado_asignacion_lotes',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Termniado', 'Terminado')], max_length=50, verbose_name='Estado asignación de lotes'),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='respuesta_integrador',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta de integrador'),
        ),
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_autorizadas', to='sample.ordenventa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='LoteAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.lote')),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='sample.ordenventa')),
            ],
            options={
                'verbose_name': 'Lote asignado',
                'verbose_name_plural': 'Lotes asignados',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock_disponible', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umd', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('cantidad_t', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad total')),
                ('precio_igv_ad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio IGV A.D.')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje descuento')),
                ('precio_igv_dd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio IGV D.D.')),
                ('afecto_impuesto', models.BooleanField(default=True, verbose_name='Afecto a impuesto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sample.listaprecios')),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sample.ordenventa')),
            ],
        ),
    ]
