# Generated by Django 4.2.21 on 2025-07-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_almacen_condicionpago_direccionenvio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='condicion_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.condicionpago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='direccion_envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.direccionenvio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='direccion_facturacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.direccionfacturacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='lista_precios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.listaprecios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='lugar_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.lugardestino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='tipo_comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.tipocomprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='tipo_embalaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.tipoembalaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.vendedor'),
            preserve_default=False,
        ),
    ]
