# Generated by Django 4.2.21 on 2025-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_ordenventa_almacen_ordenventa_condicion_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento total (%)'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total'),
        ),
    ]
