# Generated by Django 4.2.21 on 2025-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_ordenventa_descuento_total_ordenventa_impuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, unique=True)),
                ('ruc', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
