# Generated by Django 4.2.21 on 2025-07-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.cliente'),
            preserve_default=False,
        ),
    ]
