# Generated by Django 4.2.21 on 2025-07-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_ordenventa_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordenventa',
            options={'verbose_name': 'Detalle órden de venta', 'verbose_name_plural': 'Detalles órdenes de venta'},
        ),
        migrations.AlterModelOptions(
            name='personaautorizada',
            options={'verbose_name': 'Persona autorizada', 'verbose_name_plural': 'Personas autorizadas'},
        ),
        migrations.RemoveField(
            model_name='detalleordenventa',
            name='cantidad_t',
        ),
    ]
