# Generated by Django 4.2.21 on 2025-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_detalleordenventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='linea_credito_disponible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Línea de crédito disponible'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona'),
        ),
    ]
