# Generated by Django 4.2.21 on 2025-07-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_ordenventa_linea_credito_disponible_ordenventa_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaautorizada',
            name='orden_venta',
        ),
    ]
