# Generated by Django 4.2.21 on 2025-07-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_remove_personaautorizada_orden_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='persona_autorizada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.personaautorizada'),
            preserve_default=False,
        ),
    ]
