# Generated by Django 4.2.21 on 2025-07-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_ordenventa_persona_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenventa',
            name='solo_impuesto',
            field=models.BooleanField(default=False, verbose_name='Solo impuesto'),
        ),
        migrations.AlterField(
            model_name='detalleordenventa',
            name='afecto_impuesto',
            field=models.BooleanField(default=False, verbose_name='Afecto a impuesto'),
        ),
    ]
