# Generated by Django 4.2.21 on 2025-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_detalleordenventa_solo_impuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='estado_asignacion_lotes',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('terminado', 'Terminado')], default='pendiente', max_length=50, verbose_name='Estado asignación de lotes'),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='estado_sap',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('integrado', 'Integrado'), ('error', 'Error')], default='pendiente', max_length=50, verbose_name='Estado SAP'),
        ),
    ]
