# Generated by Django 4.2.21 on 2025-07-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_alter_ordenventa_estado_asignacion_lotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='asesor_comercial',
            field=models.CharField(default='Jose Lopez Ramirez', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
