# Generated by Django 4.2.21 on 2025-07-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sample.moneda', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
